version: "3.8"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Docker/backend.Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Docker/frontend.Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Docker/nginx.Dockerfile
    depends_on:
      - frontend
    ports:
      - "80:80"

volumes:
  db_data:
  redis_data:
