version: "3.8"
services:
  api_gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - market_data_service
      - order_service
      - user_service

  market_data_service:
    build: ./market_data_service
    ports:
      - "8001:8001"

  order_service:
    build: ./order_service
    ports:
      - "8002:8002"

  user_service:
    build: ./user_service
    ports:
      - "8003:8003"

  notification_service:
    build: ./notification_service
    ports:
      - "8004:8004"
